version: "3"
services:
  example:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"

  dump:
    image: alpine
    command: /bin/sh -c 'apk --no-cache -U upgrade && apk add --no-cache postgresql-client && /app/pg_dump_restore'
    volumes:
      - ./pg_dump_restore:/app/pg_dump_restore
